name: microbiome_course
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - python=3.8
  - nextflow>=21.04
  - diamond
  - cobra>=0.21.0
  - pip
  - prodigal
  - checkm
  - fastp
  - megahit
  - multiqc
  - pigz
  - sra-tools
  - gzip
  - gtdbtk
  - pip:
    - carveme
    - memote
    - /proj/gibbons/software/ibm/cplex/python/3.7/x86-64_linux/
